export const OTP_PROVIDER = Symbol('OTP_PROVIDER');
export const EMAIL_PROVIDER = Symbol('EMAIL_PROVIDER');

export const OTP_CHALLENGE_TTL_MINUTES = 10;
export const OTP_MAX_ATTEMPTS = 5;
export const EMAIL_OTP_CHALLENGE_TTL_MINUTES = 10;
export const EMAIL_OTP_RESEND_COOLDOWN_SECONDS = 60;
export const ACCESS_TOKEN_TTL_SECONDS = 15 * 60;
export const REFRESH_TOKEN_TTL_DAYS = 30;
